# -*- coding: utf-8 -*-
"""Car_Dekho_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ynLjILpK1V_o-nl4qU0JbWiQz7yNIxrk
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/1776311302-P3-Car Market Trends Analysis with Car Dekho Data.csv")
data.head()

data.describe()

data.info()

data.isnull().sum()

print(data.Car_Name.value_counts())

print(data.Fuel_Type.value_counts())

plt.pie(data.Fuel_Type.value_counts(), labels=data.Fuel_Type.value_counts().index, shadow=True, autopct='%1.1f%%', startangle=90)
plt.title('Distribution of Fuel Types')
plt.show()

data.Fuel_Type.value_counts().plot.bar()